### ISSUE TITLE
No use. The mouse keeps moving but there is no food.

### ISSUE THREAD

**Issue by rhine14586** [Gorilliath/chillquarium-reroller#1]
what‘s wrong？

**Comment by janlamch** [comment]
> what‘s wrong？

This tool does not feed the fish...

It will:
  - Buy packs
  - Open all the packs
  - Add the fish to the tank
  - Check if there are any gold or rainbow ones to save by putting into a different tank
  - Sell all the remaining babies so the process can be repeated

**Comment by Gorilliath** [comment]
> what‘s wrong？

It does not feed the fish.
It buys new fish, searches for golden and rainbow fish among the babies, and sells all that remain when there's no more golden and rainbow fish left to save.

If you want to quickly grow a tank of fish, hold down the button to drop food and move your mouse off screen (when you are in windowed mode) and let go of the button. It should bug the feeding input and should spam the food despite not holding down the button anymore. If you just keep the food to the side of the game, the fish will gather there and all feed together quite fast. If you do the bug properly you can then tab out and do something else.
